Fix PDO exception in test
Fixes the following exception after upgrading to CakePHP 4:

> 1) App\Test\TestCase\Shell\SentenceDerivationShellTest::testRun_lookAheadStepsOnOneLinkOfUnrelatedPair
> PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'datetime' cannot be null