Fix type error
Fixes the following error after upgrading to CakePHP 4:

> 1) App\Test\TestCase\Model\Table\SentencesTableTest::testGetTranslationsOf
> TypeError: Argument 1 passed to Cake\ORM\Query::aliasFields() must be of the type array, string given, called in /home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/ORM/Association.php on line 975