Fix finder return type
Fixes the following error after upgrading to CakePHP 4:

> 1) App\Test\TestCase\Model\Table\AudiosTableTest::testSentencesCountFinder
> TypeError: Return value of Cake\ORM\Table::callFinder() must be an instance of Cake\ORM\Query, int returned