Fix invalid argument exception
Fixes the following exception after upgrading to CakePHP 4:

> 1) App\Test\TestCase\Model\Table\SentencesTableTest::testGetTranslationsOf
> InvalidArgumentException: Unable to load `Transcriptions` association. Ensure foreign key in `Translations` is selected.