Fix bug caused by new constraint in tests
After upgrading to CakePHP 4.1, some tests started to fail with:

> PDOException: SQLSTATE[23000]: Integrity constraint violation: 4025 CONSTRAINT `users.settings` failed for `tatoeba_test`.`users`

This is caused by a change in how CakePHP 4.1 recognizes support for 'json'
as a native column type in its mysql driver. In CakePHP 4.0, it assumed our
10.11.14-MariaDB had no support for native json, so the fixtures generated a
users table with column 'settings' having type 'longtext'. In CakePHP 4.1,
it correctly detects support for native json and uses native type json for
users.settings instead. But merely creating the column with json type
actually automatically adds the constraint CHECK (json_valid(`settings`)).

Now there are a number of tests that create users without any settings,
and these creations all fail because of this new check. The reality is that
we haven’t use the json native type anywhere in the production database,
and the actual type for users.settings is 'blob'. So to make the fixtures
match reality, I changed the type to 'binary' (which is a CakePHP alias
that gets translated into 'blob') and added a bunch of json_encode()
to manually encode the fixture data.