Quick fix to reset and refocus textinput to add new sentence.
The input was not reset because .prepend(data) triggers the following
error:
SyntaxError: expected expression, got '<'