Fix argument count error
Fixes the following exception after upgrading to CakePHP 4:

> ArgumentCountError: Too few arguments to function Cake\Console\Shell::out(), 0 passed