Fix calls to newEntity()
Fixes the following error:

> ArgumentCountError: Too few arguments to function Cake\ORM\Table::newEntity(), 0 passed

In CakePHP 4, the behavior of calling newEntity() with no parameters
has been moved to the new newEmptyEntity() method.