Show "languages" parameter in help text
Having parameters defined restricts the number of maximum parameters,
but we need to accept an arbitrary number of language codes, e.g.:

> cake sphinx_conf eng fra spa

The VarArgsConsoleOptionParser class ConsoleOptionParser accept parameters
that are not defined instead of failing with:

> Error: Received too many arguments.