Reimplement mock proxy
After upgrading to CakePHP 4 and PHPUnit 8, there is a very strange bug that
makes phpunit it crash when attempting to create a test proxy for a
Cake\ORM\Query object. Executing the constructor of the parent class
Cake\Database\Query will result into this error:

> TypeError: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

coming from phpunit src/Framework/MockObject/Generator/proxied_method.tpl,
where $this->__phpunit_originalObject is null hence the above error.

Giving that mock proxies have been deprecated and removed in more recent
versions of phpunit, this bug will never get solved, so I reimplemented
a simple, working proxy to solve this issue.