Fix broken LimitResultsBehaviorTest
Fixes a series of LimitResultsBehaviorTest failing tests
after upgrading to CakePHP 4.5. The error was:

> InvalidArgumentException: Cannot index by path that does not exist or contains a null value. Use a callback to return a default value for that path.